/** Theme-specific composition and starter copy. Saved content is never replaced. */
export const THEME_EXPERIENCES = {
  olive: {
    layout: "folio",
    eyebrow: "Under the olive branches",
    story: "A love that keeps on growing",
    schedule: "Gathered around one table",
    sections: [
      "hero",
      "story",
      "schedule",
      "venue",
      "gallery",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  "cherry-blossom": {
    layout: "blossom",
    eyebrow: "A season for love",
    story: "When our story blossomed",
    schedule: "An afternoon in bloom",
    sections: [
      "hero",
      "countdown",
      "story",
      "gallery",
      "schedule",
      "venue",
      "rsvp",
      "calendar",
      "seating",
      "footer",
    ],
  },
  orchid: {
    layout: "atelier",
    eyebrow: "An exquisite kind of love",
    story: "Beautifully, unexpectedly us",
    schedule: "The art of celebrating",
    sections: [
      "hero",
      "date",
      "story",
      "venue",
      "schedule",
      "gallery",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  jasmine: {
    layout: "garland",
    eyebrow: "Bound together with love",
    story: "With every blessing",
    schedule: "A gathering of our families",
    sections: [
      "hero",
      "family",
      "date",
      "schedule",
      "story",
      "venue",
      "rsvp",
      "gallery",
      "seating",
      "calendar",
      "footer",
    ],
  },
  palm: {
    layout: "postcard",
    eyebrow: "Meet us in paradise",
    story: "Our favourite adventure",
    schedule: "A little island time",
    sections: [
      "hero",
      "venue",
      "countdown",
      "story",
      "schedule",
      "gallery",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  butterfly: {
    layout: "meadow",
    eyebrow: "Love has a way of finding you",
    story: "And then, our hearts took flight",
    schedule: "A day in our secret garden",
    sections: [
      "hero",
      "story",
      "gallery",
      "countdown",
      "schedule",
      "venue",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  "moon-stars": {
    layout: "celestial",
    eyebrow: "Written in the stars",
    story: "Across a thousand little moments",
    schedule: "From golden hour to starlight",
    sections: [
      "hero",
      "date",
      "story",
      "schedule",
      "gallery",
      "venue",
      "rsvp",
      "calendar",
      "seating",
      "footer",
    ],
  },
  dove: {
    layout: "vellum",
    eyebrow: "With love, always",
    story: "A promise of a lifetime",
    schedule: "Together, in peace and joy",
    sections: [
      "hero",
      "family",
      "story",
      "schedule",
      "venue",
      "rsvp",
      "gallery",
      "calendar",
      "seating",
      "footer",
    ],
  },
  rings: {
    layout: "vows",
    eyebrow: "One promise. All our tomorrows.",
    story: "The moment we knew",
    schedule: "Our vows, our forever",
    sections: [
      "hero",
      "date",
      "story",
      "schedule",
      "rsvp",
      "venue",
      "gallery",
      "calendar",
      "seating",
      "footer",
    ],
  },
  feather: {
    layout: "quill",
    eyebrow: "A love letter to forever",
    story: "A story only we could write",
    schedule: "The next beautiful chapter",
    sections: [
      "hero",
      "story",
      "date",
      "venue",
      "gallery",
      "schedule",
      "rsvp",
      "calendar",
      "seating",
      "footer",
    ],
  },
  eucalyptus: {
    layout: "herbarium",
    eyebrow: "Naturally, together",
    story: "Rooted in the little things",
    schedule: "An easy kind of beautiful",
    sections: [
      "hero",
      "story",
      "countdown",
      "venue",
      "schedule",
      "gallery",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  sunflower: {
    layout: "sunshine",
    eyebrow: "You are my golden hour",
    story: "You make the everyday golden",
    schedule: "A little sunshine, a lot of love",
    sections: [
      "hero",
      "countdown",
      "gallery",
      "story",
      "schedule",
      "venue",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  wheat: {
    layout: "harvest",
    eyebrow: "Home is wherever we are together",
    story: "Our roots, our story",
    schedule: "A countryside celebration",
    sections: [
      "hero",
      "date",
      "story",
      "venue",
      "schedule",
      "rsvp",
      "gallery",
      "seating",
      "calendar",
      "footer",
    ],
  },
  "oil-lamp": {
    layout: "heritage",
    eyebrow: "With the blessings of our families",
    story: "A light for all our tomorrows",
    schedule: "Traditions we hold close",
    sections: [
      "hero",
      "family",
      "date",
      "schedule",
      "story",
      "venue",
      "rsvp",
      "gallery",
      "calendar",
      "seating",
      "footer",
    ],
  },
  peacock: {
    layout: "jewel",
    eyebrow: "An evening of extraordinary love",
    story: "Our most treasured story",
    schedule: "A celebration in full colour",
    sections: [
      "hero",
      "date",
      "gallery",
      "story",
      "schedule",
      "venue",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  ocean: {
    layout: "tidal",
    eyebrow: "Where the ocean meets forever",
    story: "Every tide brought us here",
    schedule: "A day by the sea",
    sections: [
      "hero",
      "venue",
      "story",
      "countdown",
      "schedule",
      "gallery",
      "rsvp",
      "calendar",
      "seating",
      "footer",
    ],
  },
  "tree-of-love": {
    layout: "roots",
    eyebrow: "Rooted in love. Growing together.",
    story: "The roots of our story",
    schedule: "Gather beneath the branches",
    sections: [
      "hero",
      "family",
      "story",
      "gallery",
      "schedule",
      "venue",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
  forest: {
    layout: "forest",
    eyebrow: "Somewhere wild. Something wonderful.",
    story: "We found our way to each other",
    schedule: "A celebration beneath the canopy",
    sections: [
      "hero",
      "venue",
      "story",
      "schedule",
      "gallery",
      "countdown",
      "rsvp",
      "seating",
      "calendar",
      "footer",
    ],
  },
} as const;
export function themeExperience(id: string) {
  return id in THEME_EXPERIENCES
    ? THEME_EXPERIENCES[id as keyof typeof THEME_EXPERIENCES]
    : undefined;
}
