/** The selectable collection. Existing template IDs remain valid for saved invitations. */
export type LegacyTemplate =
  | "classic"
  | "poruwa"
  | "thali"
  | "chapel"
  | "nikkah"
  | "noir"
  | "editorial"
  | "quiet"
  | "garden"
  | "shoreline"
  | "deco"
  | "film"
  | "lotus"
  | "bloom";
export const WEDDING_THEMES = [
  {
    id: "classic",
    label: "Rose",
    base: "classic",
    description: "Rose flowers and falling rose petals.",
    element: "Rose flowers and falling rose petals",
    collection: "Romantic",
    motion: "petals",
    scene: "floral",
    palette: {
      background: "#fdf9f4",
      text: "#3c2f2b",
      primary: "#985457",
      accent: "#b28a48",
      secondary: "#f3e4df",
    },
  },
  {
    id: "lotus",
    label: "Lotus",
    base: "lotus",
    description: "Lotus flowers and falling lotus petals.",
    element: "Lotus flowers and falling lotus petals",
    collection: "Cultural",
    motion: "petals",
    scene: "floral",
    palette: {
      background: "#fcfaf5",
      text: "#40382c",
      primary: "#8b6940",
      accent: "#af8c46",
      secondary: "#eee8db",
    },
  },
  {
    id: "olive",
    label: "Olive",
    base: "garden",
    description: "Olive branches.",
    element: "Olive branches",
    collection: "Modern",
    motion: "sway",
    scene: "botanical",
    palette: {
      background: "#f6f5ed",
      text: "#303b2d",
      primary: "#526742",
      accent: "#aa925e",
      secondary: "#e4e8d9",
    },
  },
  {
    id: "cherry-blossom",
    label: "Cherry Blossom",
    base: "bloom",
    description: "Sakura flowers.",
    element: "Sakura flowers",
    collection: "Romantic",
    motion: "sway",
    scene: "canopy",
    palette: {
      background: "#fff6f5",
      text: "#51383e",
      primary: "#9c586b",
      accent: "#b17c70",
      secondary: "#f3e1e6",
    },
  },
  {
    id: "orchid",
    label: "Orchid",
    base: "chapel",
    description: "White orchids.",
    element: "White orchids",
    collection: "Romantic",
    motion: "breathe",
    scene: "botanical",
    palette: {
      background: "#faf7fc",
      text: "#45374e",
      primary: "#786086",
      accent: "#b39a80",
      secondary: "#ebe2ee",
    },
  },
  {
    id: "jasmine",
    label: "Jasmine",
    base: "lotus",
    description: "Jasmine flowers.",
    element: "Jasmine flowers",
    collection: "Romantic",
    motion: "sway",
    scene: "canopy",
    palette: {
      background: "#fffdf4",
      text: "#354333",
      primary: "#617550",
      accent: "#b49a59",
      secondary: "#eceede",
    },
  },
  {
    id: "palm",
    label: "Palm",
    base: "shoreline",
    description: "Palm leaves.",
    element: "Palm leaves",
    collection: "Modern",
    motion: "sway",
    scene: "canopy",
    palette: {
      background: "#f8f5ea",
      text: "#24463b",
      primary: "#39705a",
      accent: "#bb9257",
      secondary: "#e1e9d9",
    },
  },
  {
    id: "butterfly",
    label: "Butterfly",
    base: "bloom",
    description: "Monarch butterflies in a flower garden.",
    element: "Monarch butterflies in a flower garden",
    collection: "Romantic",
    motion: "float",
    scene: "botanical",
    palette: {
      background: "#fff9ef",
      text: "#493b32",
      primary: "#955b37",
      accent: "#ac863f",
      secondary: "#f2e6d3",
    },
  },
  {
    id: "moon-stars",
    label: "Moon & Stars",
    base: "noir",
    description: "Crescent moon and stars.",
    element: "Crescent moon and stars",
    collection: "Dark & dramatic",
    motion: "shimmer",
    scene: "night",
    palette: {
      background: "#131b30",
      text: "#f8f0df",
      primary: "#e1c694",
      accent: "#bea063",
      secondary: "#25314a",
    },
  },
  {
    id: "dove",
    label: "Dove",
    base: "chapel",
    description: "White doves.",
    element: "White doves",
    collection: "Romantic",
    motion: "float",
    scene: "botanical",
    palette: {
      background: "#fcfcf8",
      text: "#3b4551",
      primary: "#667485",
      accent: "#ae9874",
      secondary: "#e9edf0",
    },
  },
  {
    id: "rings",
    label: "Ring",
    base: "editorial",
    description: "Gold wedding rings.",
    element: "Gold wedding rings",
    collection: "Modern",
    motion: "shimmer",
    scene: "stilllife",
    palette: {
      background: "#faf6ee",
      text: "#44382d",
      primary: "#886b39",
      accent: "#aa874d",
      secondary: "#ece3d3",
    },
  },
  {
    id: "feather",
    label: "Feather",
    base: "chapel",
    description: "Soft white feathers.",
    element: "Soft white feathers",
    collection: "Romantic",
    motion: "float",
    scene: "botanical",
    palette: {
      background: "#f9f7f1",
      text: "#444039",
      primary: "#806b4c",
      accent: "#ad946d",
      secondary: "#ede7db",
    },
  },
  {
    id: "eucalyptus",
    label: "Eucalyptus",
    base: "garden",
    description: "Silver eucalyptus leaves.",
    element: "Silver eucalyptus leaves",
    collection: "Modern",
    motion: "sway",
    scene: "botanical",
    palette: {
      background: "#f3f6f1",
      text: "#30463d",
      primary: "#547765",
      accent: "#96a488",
      secondary: "#dfe9e0",
    },
  },
  {
    id: "sunflower",
    label: "Sunflower",
    base: "bloom",
    description: "Golden sunflowers.",
    element: "Golden sunflowers",
    collection: "Romantic",
    motion: "sway",
    scene: "canopy",
    palette: {
      background: "#fff9e9",
      text: "#493b22",
      primary: "#8c6817",
      accent: "#c09a36",
      secondary: "#f2e7c6",
    },
  },
  {
    id: "wheat",
    label: "Wheat",
    base: "film",
    description: "Wheat stalks at golden hour.",
    element: "Wheat stalks at golden hour",
    collection: "Editorial",
    motion: "sway",
    scene: "horizon",
    palette: {
      background: "#faf4e8",
      text: "#4a3a2c",
      primary: "#87623e",
      accent: "#b69560",
      secondary: "#eae0cf",
    },
  },
  {
    id: "candlelight",
    label: "Candlelight",
    base: "noir",
    description: "Floating wedding candles.",
    element: "Floating wedding candles",
    collection: "Dark & dramatic",
    motion: "glow",
    scene: "night",
    palette: {
      background: "#261d1b",
      text: "#faebd9",
      primary: "#e3bb86",
      accent: "#c29c62",
      secondary: "#3e302b",
    },
  },
  {
    id: "oil-lamp",
    label: "Traditional Oil Lamp",
    base: "poruwa",
    description: "Sri Lankan heritage oil lamp.",
    element: "Sri Lankan heritage oil lamp",
    collection: "Cultural",
    motion: "glow",
    scene: "stilllife",
    palette: {
      background: "#fcf5e9",
      text: "#4d3422",
      primary: "#926327",
      accent: "#ba9044",
      secondary: "#efe2c8",
    },
  },
  {
    id: "peacock",
    label: "Peacock",
    base: "deco",
    description: "Peacock feathers.",
    element: "Peacock feathers",
    collection: "Dark & dramatic",
    motion: "shimmer",
    scene: "night",
    palette: {
      background: "#132f31",
      text: "#f1eddb",
      primary: "#c7ba78",
      accent: "#b29956",
      secondary: "#22464a",
    },
  },
  {
    id: "ocean",
    label: "Ocean Waves",
    base: "shoreline",
    description: "Ocean waves.",
    element: "Ocean waves",
    collection: "Modern",
    motion: "tide",
    scene: "horizon",
    palette: {
      background: "#f1f8f8",
      text: "#264957",
      primary: "#397a89",
      accent: "#8aadb3",
      secondary: "#dcebf0",
    },
  },
  {
    id: "tree-of-love",
    label: "Tree of Love",
    base: "garden",
    description: "An oak tree at sunset.",
    element: "An oak tree at sunset",
    collection: "Romantic",
    motion: "sway",
    scene: "horizon",
    palette: {
      background: "#f8f4e9",
      text: "#37412e",
      primary: "#657348",
      accent: "#aa905f",
      secondary: "#e6e8d8",
    },
  },
  {
    id: "forest",
    label: "Greenery Forest",
    base: "garden",
    description: "A lush forest canopy, fern foliage and dappled light.",
    element: "Forest trees and fern leaves",
    collection: "Dark & dramatic",
    motion: "sway",
    scene: "forest",
    palette: {
      background: "#142c24",
      text: "#f3f3dc",
      primary: "#d0d8a5",
      accent: "#a9be84",
      secondary: "#203d30",
    },
  },
] as const;
export type CollectionTheme = (typeof WEDDING_THEMES)[number];
export type WeddingThemeId = CollectionTheme["id"];
export type SupportedTemplate = LegacyTemplate | WeddingThemeId;
export const LEGACY_TEMPLATE_IDS: readonly LegacyTemplate[] = [
  "classic",
  "poruwa",
  "thali",
  "chapel",
  "nikkah",
  "noir",
  "editorial",
  "quiet",
  "garden",
  "shoreline",
  "deco",
  "film",
  "lotus",
  "bloom",
];
// Accepts a plain string, not just SupportedTemplate — callers may hold a
// PublicWedding.template typed over the wider WeddingTemplate (which also
// covers the 16 signature ids in wedding-signature.ts; see that file's
// header). Looking one of those up here is safe and simply finds nothing.
export function weddingTheme(id: string): CollectionTheme | undefined {
  return WEDDING_THEMES.find((theme) => theme.id === id);
}
export function baseTemplate(id: SupportedTemplate): LegacyTemplate {
  return weddingTheme(id)?.base ?? (id as LegacyTemplate);
}
export function templateClasses(id: string): string {
  const base = baseTemplate(id as SupportedTemplate);
  return `theme-${base} design-${base}${base === id ? "" : ` theme-${id} design-${id}`}`;
}
