"""Direct manipulation and responsive canvas regressions, with local-only media."""
import re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect


def run(base):
    with sync_playwright() as p:
        browser=p.chromium.launch(channel='chrome',headless=True)
        context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce')
        page=context.new_page()
        errors=[]
        page.on('pageerror',lambda e: errors.append(str(e)))
        page.goto(base+'/templates',wait_until='domcontentloaded')
        expect(page.locator('[data-ready=true]')).to_be_visible(timeout=30000)
        page.get_by_role('button',name='Preview Editorial',exact=True).click()
        page.get_by_role('button',name='Make it yours',exact=True).click()
        frame=page.frame_locator('iframe[title="Wedding website preview"]')
        page.get_by_role('button',name='Elements',exact=True).click()
        page.get_by_role('button',name=re.compile(r'^Blank canvas')).click()
        expect(frame.locator('.canvas-empty')).to_be_visible()
        page.get_by_label('Canvas title',exact=True).fill('Our custom story')
        page.get_by_role('button',name='Add text element',exact=True).click()
        page.get_by_label('Layer name',exact=True).fill('Our headline')
        page.get_by_label('Element text',exact=True).fill('Made just for us.')
        layer=frame.locator('.canvas-element.element-text').first
        expect(layer).to_contain_text('Made just for us.')
        def geom(key='x'):
            return float(layer.evaluate('(el,key)=>el.style.getPropertyValue("--element-"+key)',key).rstrip('%'))
        before=geom()
        box=layer.bounding_box()
        page.mouse.move(box['x']+40,box['y']+30)
        page.mouse.down()
        page.mouse.move(box['x']+90,box['y']+65,steps=10)
        page.mouse.up()
        assert geom()>before+3,'Drag did not update the frame'
        moved=geom()
        page.get_by_role('button',name='Undo',exact=True).click()
        assert abs(geom()-before)<.1,'A drag must undo as one action'
        page.get_by_role('button',name='Redo',exact=True).click()
        assert abs(geom()-moved)<.1
        layer.focus()
        layer.press('ArrowRight')
        assert geom()>moved,'Arrow key adjustment failed'
        # Resizing and rotating are actual pointer gestures through the scaled iframe.
        old_width=geom('width')
        handle=frame.get_by_role('button',name='Resize Our headline',exact=True).bounding_box()
        page.mouse.move(handle['x']+handle['width']/2,handle['y']+handle['height']/2)
        page.mouse.down()
        page.mouse.move(handle['x']+45,handle['y']+25,steps=8)
        page.mouse.up()
        assert geom('width')>old_width
        handle=frame.get_by_role('button',name='Rotate Our headline',exact=True).bounding_box()
        page.mouse.move(handle['x']+handle['width']/2,handle['y']+handle['height']/2)
        page.mouse.down()
        page.mouse.move(handle['x']+50,handle['y']-15,steps=8)
        page.mouse.up()
        assert abs(float(layer.evaluate('el=>el.style.getPropertyValue("--element-rotation")').replace('deg','')))>1
        layer.dblclick()
        inline=frame.get_by_role('textbox',name='Edit Our headline on canvas')
        inline.fill('Every little detail, ours.')
        inline.press('Escape')
        expect(page.get_by_label('Element text',exact=True)).to_have_value('Every little detail, ours.')
        page.get_by_text('Position & size',exact=True).click()
        page.get_by_label('Element height (%)',exact=True).fill('3')
        frame.get_by_role('button',name='Fit text box',exact=True).click()
        assert geom('height')>3
        page.get_by_text('Position & size',exact=True).click()
        page.get_by_label('Element font',exact=True).select_option('manrope')
        page.get_by_label('Text color HEX',exact=True).fill('#405632')
        page.get_by_label('Text color HEX',exact=True).press('Tab')
        expect(layer).to_have_css('color','rgb(64, 86, 50)')
        # Locking protects keyboard deletion and dragging, but can be explicitly unlocked.
        page.get_by_role('button',name='Lock element',exact=True).click()
        expect(page.get_by_role('button',name='Remove element',exact=True)).to_be_disabled()
        layer.focus()
        layer.press('Delete')
        expect(frame.locator('.canvas-element')).to_have_count(1)
        page.get_by_role('button',name='Unlock element',exact=True).click()
        layer.focus()
        layer.press('Control+d')
        expect(frame.locator('.canvas-element')).to_have_count(2)
        page.get_by_role('button',name='Remove element',exact=True).click()
        expect(frame.locator('.canvas-element')).to_have_count(1)
        page.get_by_role('button',name='Undo',exact=True).click()
        expect(frame.locator('.canvas-element')).to_have_count(2)
        page.get_by_role('button',name='Redo',exact=True).click()
        expect(frame.locator('.canvas-element')).to_have_count(1)
        page.get_by_role('button',name='Select layer Our headline',exact=True).click()
        layer.focus()
        layer.press('Control+c')
        layer.press('Control+v')
        expect(frame.locator('.canvas-element')).to_have_count(2)
        page.get_by_role('button',name='All layers',exact=True).click()
        page.get_by_role('button',name='Hide layer Our headline copy',exact=True).click()
        expect(frame.locator('.canvas-element')).to_have_count(1)
        page.get_by_role('button',name='Show layer Our headline copy',exact=True).click()
        page.get_by_role('button',name='Move Our headline copy backward',exact=True).click()
        expect(frame.locator('.canvas-element').first).to_have_attribute('aria-label','Our headline copy, text layer')
        page.get_by_role('button',name='Select layer Our headline copy',exact=True).click()
        page.get_by_role('button',name='Remove element',exact=True).click()
        # Optimized local photo upload, shape appearance and safe link button.
        page.get_by_role('button',name='Add photo element',exact=True).click()
        page.locator('.canvas-inspector input[type=file]').set_input_files(str(Path('src/assets/studio-couple.webp').resolve()))
        expect(frame.locator('.element-image img')).to_have_attribute('src',re.compile('^blob:'))
        page.get_by_role('button',name='Add shape element',exact=True).click()
        page.get_by_label('Element width (%)',exact=True).fill('20')
        page.get_by_label('Element height (%)',exact=True).fill('20')
        page.get_by_role('button',name='Add button element',exact=True).click()
        page.get_by_label('Button label',exact=True).fill('Our weekend guide')
        page.get_by_label('Button destination',exact=True).fill('https://example.com/our-wedding')
        expect(frame.locator('.canvas-link')).to_contain_text('Our weekend guide')
        page.get_by_role('button',name='Show alignment grid',exact=True).click()
        expect(frame.locator('.canvas-grid')).to_have_count(1)
        page.get_by_label('Canvas zoom',exact=True).select_option('1.25')
        assert page.locator('.preview-frame-inner').evaluate('el=>getComputedStyle(el).transform').startswith('matrix(1.25')
        page.get_by_label('Canvas zoom',exact=True).select_option('fit')
        page.screenshot(path='/tmp/rovty-canvas-editor-desktop.png')
        # A phone has independent positions and type sizes; tablet uses the desktop composition.
        page.get_by_role('button',name='All layers',exact=True).click()
        page.get_by_role('button',name='Select layer Our headline',exact=True).click()
        desktop_x=geom()
        page.get_by_role('button',name='Mobile preview',exact=True).click()
        expect(frame.locator('body')).to_have_css('width','375px')
        page.get_by_text('Position & size',exact=True).click()
        page.get_by_label('Horizontal position (%)',exact=True).fill('4')
        page.get_by_label('Phone text size',exact=True).fill('30')
        assert geom('mobile-x')==4
        assert geom()==desktop_x
        page.get_by_role('button',name='Tablet preview',exact=True).click()
        expect(frame.locator('body')).to_have_css('width','768px')
        assert geom()==desktop_x
        page.get_by_role('button',name='Mobile preview',exact=True).click()
        page.get_by_role('button',name='All layers',exact=True).click()
        page.get_by_role('button',name='Arrange layers for a phone',exact=True).click()
        expect(page.get_by_text('Phone layout arranged. Your desktop layout is unchanged.',exact=True)).to_be_visible()
        assert geom()==desktop_x
        # Template changes retain custom canvases and every authored element.
        page.get_by_role('button',name='Designs',exact=True).click()
        page.get_by_role('button',name='Switch to Deco',exact=True).click()
        expect(frame.locator('.canvas-element')).to_have_count(4)
        expect(frame.locator('.canvas-text')).to_contain_text(['Every little detail, ours.'])
        page.get_by_role('button',name='Preview & publish',exact=True).click()
        review=page.frame_locator('dialog iframe')
        expect(review.locator('.custom-canvas')).to_have_count(1)
        expect(review.locator('.canvas-editing')).to_have_count(0)
        expect(review.get_by_role('link',name='Our weekend guide',exact=False)).to_have_attribute('href','https://example.com/our-wedding')
        page.get_by_role('button',name='Back to editing',exact=True).click()
        page.wait_for_function('JSON.parse(localStorage.getItem("rovty-wed-studio-v1"))?.wedding?.template === "deco"')
        page.reload(wait_until='domcontentloaded')
        expect(page.locator('[data-ready=true]')).to_be_visible(timeout=30000)
        page.get_by_role('button',name='Continue your draft',exact=False).click()
        expect(frame.locator('.canvas-element')).to_have_count(4)
        expect(frame.locator('.canvas-text')).to_contain_text(['Every little detail, ours.'])
        expect(frame.locator('.element-image img')).to_have_count(0) # expired blob previews are not restored
        page.get_by_role('button',name='Elements',exact=True).click()
        page.get_by_label('Choose a custom canvas',exact=True).select_option(label='Our custom story')
        page.get_by_role('button',name='Duplicate canvas',exact=False).click()
        expect(frame.locator('.custom-canvas')).to_have_count(2)
        page.get_by_role('button',name='Remove canvas',exact=False).click()
        expect(frame.locator('.custom-canvas')).to_have_count(1)
        # Section visibility and cropping are optional overrides, applied only to that section.
        page.get_by_role('button',name='Sections',exact=True).click()
        page.get_by_role('button',name='Our story Click to customize',exact=True).click()
        page.get_by_text('Layout & spacing',exact=True).click()
        page.get_by_label('Show this section on',exact=True).select_option('mobile')
        page.get_by_role('button',name='Desktop preview',exact=True).click()
        expect(frame.locator('.section-story')).to_be_hidden()
        page.get_by_role('button',name='Mobile preview',exact=True).click()
        expect(frame.locator('.section-story')).to_be_visible()
        page.get_by_label('Text alignment',exact=True).select_option('center')
        expect(frame.locator('.site-story-copy')).to_have_css('text-align','center')
        page.get_by_label('Section photo vertical position',exact=True).fill('80')
        expect(frame.locator('.site-story-image img')).to_have_css('object-position','50% 80%')
        # The inspector and canvas remain usable on a real narrow phone viewport.
        page.set_viewport_size({'width':390,'height':844})
        page.get_by_role('button',name='Elements',exact=True).click()
        page.get_by_label('Choose a custom canvas',exact=True).select_option(label='Our custom story')
        page.get_by_role('button',name='Select layer Our headline',exact=True).click()
        page.get_by_label('Element text',exact=True).fill('Designed on a phone.')
        page.get_by_role('button',name='Live preview',exact=True).click()
        expect(frame.locator('.canvas-text')).to_contain_text(['Designed on a phone.'])
        expect(frame.locator('.canvas-board')).to_be_in_viewport(ratio=0.2)
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        page.screenshot(path='/tmp/rovty-canvas-editor-phone.png')
        page.get_by_role('button',name='Edit selected element',exact=False).click()
        expect(page.get_by_label('Element text',exact=True)).to_be_visible()
        assert not errors, errors
        context.close()
        browser.close()
        print('PASS: canvas drag, resize, rotate, inline text, keyboard shortcuts, undo, layers, uploads, grid, zoom, phone layouts, tablet, template switch, public renderer, draft restore and phone editor.',flush=True)
