// The 14 invitation designs, as full typographic systems — transcribed from
// the "Rovty Wed Landing B" design canvas, and matching the same 14 ids/
// labels/descriptions as WEDDING_TEMPLATES in src/lib/wedding.ts (the actual
// product's template list). This file adds the per-template colour/font
// values the landing page's live builder and gallery need to render a
// miniature of each design; src/lib/wedding.ts stays the source of truth for
// which templates exist.
export interface WedTemplateTheme {
  id: string;
  label: string;
  desc: string;
  /** Full CSS background (gradient) for the live phone preview screen. */
  bg: string;
  /** Flat swatch approximating `bg`, for the gallery row's colour chip. */
  swatchBg: string;
  fg: string;
  muted: string;
  border: string;
  gold: string;
  rose: string;
  grad: string;
  btnInk: string;
  /** Corner radius (px) for cards. */
  rad: number;
  /** Corner radius (px, capped at 999 = pill) for buttons. */
  brad: number;
  /** Display (couple-names) font-family CSS value, quotes included. */
  disp: string;
  dw: number;
  dt: "none" | "uppercase";
  dls: string;
  ditl?: "italic";
  /** Kicker/eyebrow font-family CSS value, quotes included. */
  kf: string;
  ks: number;
  kt: "none" | "uppercase";
  kls: string;
  ki: "normal" | "italic";
  /** Script (ampersand / closing line) font-family CSS value, quotes included. */
  scr: string;
  dark?: boolean;
}

export const WED_TEMPLATES: WedTemplateTheme[] = [
  {
    id: "classic",
    label: "Classic",
    desc: "Rose & gold, falling petals.",
    bg: "linear-gradient(180deg,#fdf9f4 0%,#f9ebe6 48%,#fcf6ec 100%)",
    swatchBg: "#fdf9f4",
    fg: "#3c2f2b",
    muted: "#7d6a63",
    border: "rgba(201,151,79,.26)",
    gold: "#c9974f",
    rose: "#a06c33",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#3a2e1c",
    rad: 24,
    brad: 999,
    disp: '"Playfair Display",serif',
    dw: 500,
    dt: "none",
    dls: "-0.01em",
    kf: '"Cormorant Garamond",serif',
    ks: 17,
    kt: "none",
    kls: ".01em",
    ki: "italic",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "poruwa",
    label: "Poruwa",
    desc: "Traditional, antique gold.",
    bg: "linear-gradient(180deg,#fdf7ee,#f7ece0)",
    swatchBg: "#fdf7ee",
    fg: "#3a2b1e",
    muted: "#82705c",
    border: "rgba(181,137,63,.24)",
    gold: "#b5893f",
    rose: "#8a6428",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#3a2e1c",
    rad: 4,
    brad: 4,
    disp: '"Cinzel",serif',
    dw: 600,
    dt: "none",
    dls: ".06em",
    kf: '"Mukta",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".34em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "thali",
    label: "Thali",
    desc: "Pastel marigold & gold.",
    bg: "linear-gradient(180deg,#fdf5ea,#fbeade)",
    swatchBg: "#fdf5ea",
    fg: "#3f291d",
    muted: "#8a6b57",
    border: "rgba(217,154,91,.26)",
    gold: "#d99a5b",
    rose: "#a2612f",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#3a2e1c",
    rad: 14,
    brad: 999,
    disp: '"Rozha One",serif',
    dw: 400,
    dt: "none",
    dls: "0",
    kf: '"Mukta",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".28em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "chapel",
    label: "Chapel",
    desc: "Powder blue & pearl.",
    bg: "linear-gradient(180deg,#fafbfd,#eef2f8)",
    swatchBg: "#fafbfd",
    fg: "#2b3550",
    muted: "#6c7793",
    border: "rgba(43,53,80,.14)",
    gold: "#b99a5b",
    rose: "#4a5876",
    grad: "linear-gradient(135deg,#5b6a8c,#33405e)",
    btnInk: "#f8fafd",
    rad: 6,
    brad: 6,
    disp: '"Cormorant Garamond",serif',
    dw: 500,
    dt: "none",
    dls: ".02em",
    kf: '"Lato",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".36em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "nikkah",
    label: "Nikkah",
    desc: "Pastel sage & gold.",
    bg: "linear-gradient(180deg,#f7fbf8,#eef5f0)",
    swatchBg: "#f7fbf8",
    fg: "#26382f",
    muted: "#6d8177",
    border: "rgba(38,56,47,.14)",
    gold: "#a98f4e",
    rose: "#4f6b58",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#3a2e1c",
    rad: 4,
    brad: 4,
    disp: '"Amiri",serif',
    dw: 700,
    dt: "none",
    dls: "0",
    kf: '"Jost",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".3em",
    ki: "normal",
    scr: '"Amiri",serif',
  },
  {
    id: "noir",
    label: "Noir",
    desc: "Champagne on charcoal.",
    bg: "linear-gradient(180deg,#17161a,#211f25)",
    swatchBg: "#17161a",
    fg: "#f3eee4",
    muted: "#a9a196",
    border: "rgba(243,238,228,.18)",
    gold: "#d8b877",
    rose: "#e8cd94",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#20190f",
    rad: 4,
    brad: 4,
    disp: '"Bodoni Moda",serif',
    dw: 500,
    dt: "uppercase",
    dls: ".08em",
    kf: '"Jost",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".42em",
    ki: "normal",
    scr: '"Bodoni Moda",serif',
    dark: true,
  },
  {
    id: "editorial",
    label: "Editorial",
    desc: "Oat, clay & gold rules.",
    bg: "linear-gradient(180deg,#faf7f3,#f2ebe4)",
    swatchBg: "#faf7f3",
    fg: "#2a231e",
    muted: "#786a5f",
    border: "rgba(42,35,30,.16)",
    gold: "#c08e6d",
    rose: "#95604a",
    grad: "linear-gradient(135deg,#3a302a,#221c18)",
    btnInk: "#faf7f3",
    rad: 2,
    brad: 2,
    disp: '"Instrument Serif",serif',
    dw: 400,
    dt: "none",
    dls: "-.02em",
    kf: '"Archivo",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".22em",
    ki: "normal",
    scr: '"Instrument Serif",serif',
  },
  {
    id: "quiet",
    label: "Quiet",
    desc: "Pearl white, gold hairline.",
    bg: "linear-gradient(180deg,#ffffff,#f7f5f2)",
    swatchBg: "#ffffff",
    fg: "#211f1d",
    muted: "#7b756e",
    border: "rgba(33,31,29,.12)",
    gold: "#c0a878",
    rose: "#8a7748",
    grad: "linear-gradient(135deg,#2c2926,#181614)",
    btnInk: "#fbfaf8",
    rad: 2,
    brad: 2,
    disp: '"Manrope",sans-serif',
    dw: 800,
    dt: "uppercase",
    dls: "-.02em",
    kf: '"Manrope",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".3em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "garden",
    label: "Garden",
    desc: "Pastel sage & cream.",
    bg: "linear-gradient(180deg,#f7faf3,#eef4e9)",
    swatchBg: "#f7faf3",
    fg: "#2c3626",
    muted: "#6c7c60",
    border: "rgba(44,54,38,.13)",
    gold: "#8fa673",
    rose: "#55703f",
    grad: "linear-gradient(135deg,#7c9761,#4e6b3b)",
    btnInk: "#f7faf2",
    rad: 22,
    brad: 999,
    disp: '"Newsreader",serif',
    dw: 400,
    dt: "none",
    dls: "0",
    ditl: "italic",
    kf: '"Newsreader",serif',
    ks: 15,
    kt: "none",
    kls: ".01em",
    ki: "italic",
    scr: '"Newsreader",serif',
  },
  {
    id: "shoreline",
    label: "Shoreline",
    desc: "Pastel aqua & sand.",
    bg: "linear-gradient(180deg,#fcf8f1,#ecf5f5)",
    swatchBg: "#fcf8f1",
    fg: "#1f3c45",
    muted: "#65838b",
    border: "rgba(31,60,69,.13)",
    gold: "#8bb6bd",
    rose: "#3a6d78",
    grad: "linear-gradient(135deg,#7fadb6,#39707c)",
    btnInk: "#f7fbfb",
    rad: 18,
    brad: 999,
    disp: '"Tenor Sans",sans-serif',
    dw: 400,
    dt: "none",
    dls: ".06em",
    kf: '"Nunito Sans",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".3em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "deco",
    label: "Deco",
    desc: "Pastel jade & gilt.",
    bg: "linear-gradient(180deg,#f6f3ea,#eef0e7)",
    swatchBg: "#f6f3ea",
    fg: "#1f4241",
    muted: "#5f7b7a",
    border: "rgba(31,66,65,.18)",
    gold: "#c2a15c",
    rose: "#7d6528",
    grad: "linear-gradient(135deg,#ebd3a0,#c9a45c)",
    btnInk: "#3a2e1c",
    rad: 0,
    brad: 0,
    disp: '"Poiret One",sans-serif',
    dw: 400,
    dt: "uppercase",
    dls: ".18em",
    kf: '"Josefin Sans",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".4em",
    ki: "normal",
    scr: '"Poiret One",sans-serif',
  },
  {
    id: "film",
    label: "Film",
    desc: "Warm sepia, photo-led.",
    bg: "linear-gradient(180deg,#161311,#1e1a17)",
    swatchBg: "#161311",
    fg: "#f4ece1",
    muted: "#a89c8d",
    border: "rgba(244,236,225,.18)",
    gold: "#d9c3a0",
    rose: "#f0e3cf",
    grad: "linear-gradient(135deg,#efe3d1,#cdb494)",
    btnInk: "#241d16",
    rad: 3,
    brad: 3,
    disp: '"Crimson Pro",serif',
    dw: 400,
    dt: "none",
    dls: ".01em",
    kf: '"IBM Plex Sans",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".28em",
    ki: "normal",
    scr: '"Crimson Pro",serif',
    dark: true,
  },
  {
    id: "lotus",
    label: "Lotus",
    desc: "Ivory & gold, falling lotus.",
    bg: "linear-gradient(180deg,#fdf9f0 0%,#f6eddc 52%,#fbf5e8 100%)",
    swatchBg: "#fdf9f0",
    fg: "#2f2a22",
    muted: "#8a7b60",
    border: "rgba(192,153,63,.28)",
    gold: "#c0993f",
    rose: "#96712a",
    grad: "linear-gradient(135deg,#e8cf95,#c0993f)",
    btnInk: "#2f2a22",
    rad: 6,
    brad: 6,
    disp: '"Playfair Display",serif',
    dw: 500,
    dt: "none",
    dls: ".01em",
    kf: '"Lato",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".3em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
  {
    id: "bloom",
    label: "Bloom",
    desc: "Blush rose-gold, arched.",
    bg: "linear-gradient(180deg,#fdf8f6,#f7eee9)",
    swatchBg: "#fdf8f6",
    fg: "#3f2e2b",
    muted: "#8b736e",
    border: "rgba(63,46,43,.12)",
    gold: "#d3a293",
    rose: "#a06455",
    grad: "linear-gradient(135deg,#e2b6a4,#b07463)",
    btnInk: "#fff8f5",
    rad: 18,
    brad: 999,
    disp: '"Marcellus",serif',
    dw: 400,
    dt: "none",
    dls: ".01em",
    kf: '"Outfit",sans-serif',
    ks: 10,
    kt: "uppercase",
    kls: ".3em",
    ki: "normal",
    scr: '"Cormorant Garamond",serif',
  },
];
