/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarDoticsRouteImport } from './routes/calendar[.]ics'
import { Route as PeoplesBankRouteImport } from './routes/peoples-bank'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugCalendarDoticsRouteImport } from './routes/$slug.calendar[.]ics'
import { Route as SlugSeatingRouteImport } from './routes/$slug.seating'
import { Route as ApiTeamRouteImport } from './routes/api.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDoticsRoute = CalendarDoticsRouteImport.update({
  id: '/calendar.ics',
  path: '/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplesBankRoute = PeoplesBankRouteImport.update({
  id: '/peoples-bank',
  path: '/peoples-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCalendarDoticsRoute = SlugCalendarDoticsRouteImport.update({
  id: '/calendar.ics',
  path: '/calendar.ics',
  getParentRoute: () => SlugRoute,
} as any)
const SlugSeatingRoute = SlugSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => SlugRoute,
} as any)
const ApiTeamRoute = ApiTeamRouteImport.update({
  id: '/api/team',
  path: '/api/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/peoples-bank': typeof PeoplesBankRoute
  '/rsvp': typeof RsvpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/thank-you': typeof ThankYouRoute
  '/thankyou': typeof ThankyouRoute
  '/$slug/calendar.ics': typeof SlugCalendarDoticsRoute
  '/$slug/seating': typeof SlugSeatingRoute
  '/api/team': typeof ApiTeamRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/peoples-bank': typeof PeoplesBankRoute
  '/rsvp': typeof RsvpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/thank-you': typeof ThankYouRoute
  '/thankyou': typeof ThankyouRoute
  '/$slug/calendar.ics': typeof SlugCalendarDoticsRoute
  '/$slug/seating': typeof SlugSeatingRoute
  '/api/team': typeof ApiTeamRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/peoples-bank': typeof PeoplesBankRoute
  '/rsvp': typeof RsvpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/thank-you': typeof ThankYouRoute
  '/thankyou': typeof ThankyouRoute
  '/$slug/calendar.ics': typeof SlugCalendarDoticsRoute
  '/$slug/seating': typeof SlugSeatingRoute
  '/api/team': typeof ApiTeamRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/calendar.ics'
    | '/peoples-bank'
    | '/rsvp'
    | '/sitemap.xml'
    | '/sso'
    | '/thank-you'
    | '/thankyou'
    | '/$slug/calendar.ics'
    | '/$slug/seating'
    | '/api/team'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/calendar.ics'
    | '/peoples-bank'
    | '/rsvp'
    | '/sitemap.xml'
    | '/sso'
    | '/thank-you'
    | '/thankyou'
    | '/$slug/calendar.ics'
    | '/$slug/seating'
    | '/api/team'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/calendar.ics'
    | '/peoples-bank'
    | '/rsvp'
    | '/sitemap.xml'
    | '/sso'
    | '/thank-you'
    | '/thankyou'
    | '/$slug/calendar.ics'
    | '/$slug/seating'
    | '/api/team'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CalendarDoticsRoute: typeof CalendarDoticsRoute
  PeoplesBankRoute: typeof PeoplesBankRoute
  RsvpRoute: typeof RsvpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SsoRoute: typeof SsoRoute
  ThankYouRoute: typeof ThankYouRoute
  ThankyouRoute: typeof ThankyouRoute
  ApiTeamRoute: typeof ApiTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar.ics': {
      id: '/calendar.ics'
      path: '/calendar.ics'
      fullPath: '/calendar.ics'
      preLoaderRoute: typeof CalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peoples-bank': {
      id: '/peoples-bank'
      path: '/peoples-bank'
      fullPath: '/peoples-bank'
      preLoaderRoute: typeof PeoplesBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/calendar.ics': {
      id: '/$slug/calendar.ics'
      path: '/calendar.ics'
      fullPath: '/$slug/calendar.ics'
      preLoaderRoute: typeof SlugCalendarDoticsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/seating': {
      id: '/$slug/seating'
      path: '/seating'
      fullPath: '/$slug/seating'
      preLoaderRoute: typeof SlugSeatingRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/team': {
      id: '/api/team'
      path: '/api/team'
      fullPath: '/api/team'
      preLoaderRoute: typeof ApiTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SlugRouteChildren {
  SlugCalendarDoticsRoute: typeof SlugCalendarDoticsRoute
  SlugSeatingRoute: typeof SlugSeatingRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugCalendarDoticsRoute: SlugCalendarDoticsRoute,
  SlugSeatingRoute: SlugSeatingRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CalendarDoticsRoute: CalendarDoticsRoute,
  PeoplesBankRoute: PeoplesBankRoute,
  RsvpRoute: RsvpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SsoRoute: SsoRoute,
  ThankYouRoute: ThankYouRoute,
  ThankyouRoute: ThankyouRoute,
  ApiTeamRoute: ApiTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
