-- RSVP hardening.
--
-- 1. One RSVP row per guest. submit_rsvp used to INSERT unconditionally, so a
--    guest (or anyone holding their code) could append unlimited rows; the
--    admin then had to sort by created_at to find "the latest". It now
--    upserts on (wedding_id, guest_code) and keeps an updated_at, so the
--    table is bounded by the guest list and "latest" is simply "the row".
--    Existing duplicates are collapsed to the most recent before the unique
--    constraint is added.
--
-- 2. Public RPC throttling. get_guest_by_code / submit_rsvp / get_seating_by_code
--    are callable anonymously and keyed only by a slug + guest code, so code
--    guessing must be expensive. rpc_attempts records failed lookups per
--    (slug, client) and the RPCs refuse to answer once a client has made too
--    many failed guesses against a wedding in a rolling window. The client key
--    is the caller's IP as reported by PostgREST's request headers; when that
--    header is missing (local dev) throttling still works per-slug.
--
-- 3. Guest codes generated by the admin are now 8 characters (was 6) — see
--    src/components/admin/utils.ts. Existing 6-char codes keep working.

-- ── 1. One RSVP per guest ────────────────────────────────────────────────

alter table public.rsvps add column if not exists updated_at timestamptz not null default now();

-- Collapse historical duplicates: keep the newest row per guest.
delete from public.rsvps r
using public.rsvps newer
where newer.wedding_id = r.wedding_id
  and newer.guest_code = r.guest_code
  and newer.created_at > r.created_at;

create unique index if not exists rsvps_wedding_guest_unique
  on public.rsvps (wedding_id, guest_code);

-- ── 2. Attempt throttling for the anonymous RPCs ─────────────────────────

create table if not exists public.rpc_attempts (
  slug text not null,
  client text not null,
  attempted_at timestamptz not null default now()
);
create index if not exists rpc_attempts_lookup on public.rpc_attempts (slug, client, attempted_at desc);
-- Service role only; anon/authenticated never touch this table directly,
-- only through the security-definer functions below.
revoke all on public.rpc_attempts from anon, authenticated;
alter table public.rpc_attempts enable row level security;

create or replace function public._rpc_client_key()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(split_part(current_setting('request.headers', true)::json ->> 'cf-connecting-ip', ',', 1), ''),
    nullif(split_part(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ',', 1), ''),
    'unknown'
  );
$$;

-- True when this client has failed more than _limit times against _slug in
-- the last _window. Also prunes old rows opportunistically so the table
-- stays small without a scheduled job.
create or replace function public._rpc_throttled(_slug text, _limit int default 20, _window interval default '15 minutes')
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  _client text := public._rpc_client_key();
  _n int;
begin
  delete from public.rpc_attempts where attempted_at < now() - interval '1 day';
  select count(*) into _n
  from public.rpc_attempts
  where slug = lower(trim(_slug)) and client = _client and attempted_at > now() - _window;
  return _n >= _limit;
end;
$$;

create or replace function public._rpc_record_failure(_slug text)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.rpc_attempts (slug, client) values (lower(trim(_slug)), public._rpc_client_key());
$$;

revoke all on function public._rpc_client_key() from public;
revoke all on function public._rpc_throttled(text, int, interval) from public;
revoke all on function public._rpc_record_failure(text) from public;

-- ── 3. RPCs, rewritten with throttling + upsert ──────────────────────────

create or replace function public.get_guest_by_code(_slug text, _code text)
returns table (code text, name text, title text, seats int)
language plpgsql
-- volatile (not stable): records failed attempts as a side effect
security definer
set search_path = public
as $$
begin
  if public._rpc_throttled(_slug) then
    return;
  end if;

  return query
    select g.code, g.name, g.title, g.seats
    from public.guests g
    join public.weddings w on w.id = g.wedding_id
    where w.slug = lower(trim(_slug))
      and w.published = true
      and g.code = upper(trim(_code))
    limit 1;

  if not found then
    perform public._rpc_record_failure(_slug);
  end if;
end;
$$;
grant execute on function public.get_guest_by_code(text, text) to anon, authenticated;

create or replace function public.submit_rsvp(_slug text, _code text, _attending boolean, _message text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  _wedding_id uuid;
  _id uuid;
  _norm text := upper(trim(_code));
begin
  if public._rpc_throttled(_slug) then
    raise exception 'Too many attempts. Please try again later.';
  end if;

  select w.id into _wedding_id
  from public.weddings w
  where w.slug = lower(trim(_slug)) and w.published = true;

  if _wedding_id is null then
    perform public._rpc_record_failure(_slug);
    raise exception 'Invalid invitation link';
  end if;

  if not exists (select 1 from public.guests where wedding_id = _wedding_id and code = _norm) then
    perform public._rpc_record_failure(_slug);
    raise exception 'Invalid invitation code';
  end if;

  insert into public.rsvps (wedding_id, guest_code, attending, message)
  values (_wedding_id, _norm, _attending, nullif(trim(coalesce(_message, '')), ''))
  on conflict (wedding_id, guest_code) do update
    set attending = excluded.attending,
        message = excluded.message,
        updated_at = now()
  returning id into _id;
  return _id;
end;
$$;
grant execute on function public.submit_rsvp(text, text, boolean, text) to anon, authenticated;

create or replace function public.get_seating_by_code(_slug text, _code text)
returns json
language plpgsql
-- volatile (not stable): records failed attempts as a side effect
security definer
set search_path = public
as $$
declare
  _wedding_id uuid;
  _seating_published boolean;
  _norm text := upper(trim(_code));
  _guest record;
  _assignment record;
  _tablemates json;
begin
  if public._rpc_throttled(_slug) then
    return null;
  end if;

  select w.id into _wedding_id
  from public.weddings w
  where w.slug = lower(trim(_slug)) and w.published = true;
  if _wedding_id is null then
    perform public._rpc_record_failure(_slug);
    return null;
  end if;

  select published into _seating_published
  from public.seating_config where wedding_id = _wedding_id;
  if not coalesce(_seating_published, false) then
    return null;
  end if;

  select code, name, title, seats into _guest
  from public.guests where wedding_id = _wedding_id and code = _norm;
  if not found then
    perform public._rpc_record_failure(_slug);
    return null;
  end if;

  select sa.id, sa.table_id, st.table_number, st.table_name, st.map_x, st.map_y
  into _assignment
  from public.seating_assignments sa
  join public.seating_tables st on st.id = sa.table_id
  where sa.wedding_id = _wedding_id and sa.guest_code = _norm and st.is_active;
  if not found then
    return null;
  end if;

  select json_agg(json_build_object(
    'name', g.name,
    'is_current', g.code = _norm
  ) order by (g.code = _norm) desc, g.name)
  into _tablemates
  from public.seating_assignments sa
  join public.guests g on g.wedding_id = sa.wedding_id and g.code = sa.guest_code
  where sa.table_id = _assignment.table_id;

  return json_build_object(
    'guest_name', _guest.name,
    'guest_code', _guest.code,
    'table_number', _assignment.table_number,
    'table_name', _assignment.table_name,
    'map_x', _assignment.map_x,
    'map_y', _assignment.map_y,
    'tablemates', coalesce(_tablemates, '[]'::json)
  );
end;
$$;
grant execute on function public.get_seating_by_code(text, text) to anon, authenticated;
